name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint import
        run: python -c "import flask, flask_sqlalchemy, flask_migrate"
      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

